dist: xenial
language: scala

jdk:
  - openjdk11

scala:
  - 2.12.12
  - 2.13.3

env:
  matrix:
    - SCALAJS_VERSION="0.6.33"
    - SCALAJS_VERSION=""

script:
  - sbt fullOptJS

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.cache/coursier
